# Generated by Django 3.1.6 on 2021-04-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reportincident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Corporate Headoffice', 'Corporate Headoffice'), ('Operations Departments', 'Operations Departments'), ('Work Station', 'Work Station'), ('Marketing Division', 'Marketing Division')], default='1', max_length=100)),
                ('desc', models.CharField(max_length=300, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('inc_location', models.CharField(max_length=100, null=True)),
                ('severety', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Fatal', 'Fatal')], default='1', max_length=100)),
                ('cause', models.CharField(max_length=300, null=True)),
                ('action', models.CharField(max_length=200, null=True)),
                ('environment', models.BooleanField(default=False, verbose_name='environment')),
                ('injury', models.BooleanField(default=False, verbose_name='injury')),
                ('damage', models.BooleanField(default=False, verbose_name='damage')),
                ('vehicle', models.BooleanField(default=False, verbose_name='vehicle')),
            ],
        ),
    ]
